platform :ios, '8.0'

target :'uChat' do

pod 'SDWebImage'
pod 'UMengAnalytics'
pod 'FMDB'
pod 'AFNetworking'
pod 'RongCloudIMKit', '~> 2.6.6'
pod 'Reachability'
pod 'MJRefresh'
pod 'TTRangeSlider'
pod 'Firebase/Core'
pod 'Firebase/AdMob'
pod 'Fabric'
pod 'Crashlytics'
pod 'MBProgressHUD'

end
